# Generated by Django 3.1.4 on 2020-12-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField(max_length=200)),
                ('inning', models.IntegerField(max_length=200)),
                ('batting_team', models.CharField(max_length=200)),
                ('bowling_team', models.CharField(max_length=200)),
                ('over', models.IntegerField(max_length=200)),
                ('ball', models.IntegerField(max_length=200)),
                ('batsman', models.CharField(max_length=200)),
                ('non_striker', models.CharField(max_length=200)),
                ('bowler', models.CharField(max_length=200)),
                ('is_super_over', models.BooleanField()),
                ('wide_runs', models.IntegerField(max_length=200)),
                ('bye_runs', models.IntegerField(max_length=200)),
                ('legbye_runs', models.IntegerField(max_length=200)),
                ('noball_runs', models.IntegerField(max_length=200)),
                ('penalty_runs', models.IntegerField(max_length=200)),
                ('batsman_runs', models.IntegerField(max_length=200)),
                ('extra_runs', models.IntegerField(max_length=200)),
                ('total_runs', models.IntegerField(max_length=200)),
                ('player_dismissed', models.CharField(max_length=200)),
                ('dismissal_kind', models.CharField(max_length=200)),
                ('fielder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)])),
                ('city', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=200)),
                ('toss_winner', models.CharField(max_length=200)),
                ('toss_decision', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('dl_applied', models.BooleanField()),
                ('winner', models.CharField(max_length=200)),
                ('win_by_runs', models.IntegerField(max_length=200)),
                ('win_by_wickets', models.IntegerField(max_length=200)),
                ('player_of_match', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('umpire1', models.CharField(max_length=200)),
                ('umpire2', models.CharField(max_length=200)),
                ('umpire3', models.CharField(max_length=200)),
            ],
        ),
    ]
