# Generated by Django 3.1.4 on 2020-12-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='ball',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='batsman_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='bye_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='extra_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='inning',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='legbye_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='match_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='noball_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='over',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='penalty_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='total_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='wide_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='win_by_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='win_by_wickets',
            field=models.IntegerField(),
        ),
    ]
